language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - next
before_script:
  - npm install -g
@angular/cli
script:
- ng lint
- ng build --prod --base-href
https://cisowscy-com-software.github.io/haplo-ft/
